import { Routes } from '@angular/router';
import { Home } from './component/shared/home/home';
import { RoutedAdminPlist } from './component/blog/routed-admin-plist/routed-admin-plist';
import { RoutedAdminView } from './component/blog/routed-admin-view/routed-admin-view';
import { RoutedUserPlist } from './component/blog/routed-user-plist/routed-user-plist';
import { RoutedUserView } from './component/blog/routed-user-view/routed-user-view';
import { RoutedAdminEdit } from './component/blog/routed-admin-edit/routed-admin-edit';
import { RoutedAdminNew } from './component/blog/routed-admin-new/routed-admin-new';
import { RoutedAdminRemove } from './component/blog/routed-admin-remove/routed-admin-remove';
import { SoaresRoutedAdminPlist } from './component/soares/routed-admin-plist/routed-admin-plist';
import { SoaresRoutedAdminNew } from './component/soares/routed-admin-new/routed-admin-new';
import { SoaresRoutedAdminEdit } from './component/soares/routed-admin-edit/routed-admin-edit';
import { SoaresRoutedAdminRemove } from './component/soares/routed-admin-remove/routed-admin-remove';
import { SoaresRoutedUserPlist } from './component/soares/routed-user-plist/routed-user-plist';
import { PreguntasPorTemaComponent } from './component/soares/preguntas-por-tema/preguntas-por-tema';

//imports Alan
import { RoutedAlcanyizMenu } from './component/alcanyiz/routed-alcanyiz-menu/routed-alcanyiz-menu'
import { RoutedAlcanyizUserView } from './component/alcanyiz/routed-alcanyiz-user-view/routed-alcanyiz-user-view';
import { RoutedAlcanyizAdminQuestionlist } from './component/alcanyiz/routed-alcanyiz-admin-questionlist/routed-alcanyiz-admin-questionlist';
import { RoutedAlcanyizAdminView } from './component/alcanyiz/routed-alcanyiz-admin-view/routed-alcanyiz-admin-view';
import { RoutedAlcanyizUserList } from './component/alcanyiz/routed-alcanyiz-user-list/routed-alcanyiz-user-list';
import { RoutedAlcanyizAdminCreate } from './component/alcanyiz/routed-alcanyiz-admin-create/routed-alcanyiz-admin-create';
import { RoutedAlcanyizAdminEdit } from './component/alcanyiz/routed-alcanyiz-admin-edit/routed-alcanyiz-admin-edit';
import { RoutedAlcanyizAdminRemove } from './component/alcanyiz/routed-alcanyiz-admin-remove/routed-alcanyiz-admin-remove';
import { RoutedAlcanyizGame } from './component/alcanyiz/routed-alcanyiz-game/routed-alcanyiz-game';

export const routes: Routes = [
  { path: '', component: Home },
  { path: 'blog', component: RoutedUserPlist },
  { path: 'blog/post/:id', component: RoutedUserView },
  { path: 'blog/plist', component: RoutedAdminPlist },
  { path: 'blog/view/:id', component: RoutedAdminView },
  { path: 'blog/new', component: RoutedAdminNew },
  { path: 'blog/edit/:id', component: RoutedAdminEdit },
  { path: 'blog/remove/:id', component: RoutedAdminRemove },
  { path: 'alcanyiz', component: RoutedAlcanyizMenu },
  { path: 'alcanyiz/allquestion', component: RoutedAlcanyizUserList },
  { path: 'alcanyiz/question/:id', component: RoutedAlcanyizUserView },
  { path: 'alcanyiz/questionlist', component: RoutedAlcanyizAdminQuestionlist },
  { path: 'alcanyiz/questionview/:id', component: RoutedAlcanyizAdminView },
  { path: 'alcanyiz/questioncreate', component: RoutedAlcanyizAdminCreate },
  { path: 'alcanyiz/questionedit/:id', component: RoutedAlcanyizAdminEdit },
  { path: 'alcanyiz/questionremove/:id', component: RoutedAlcanyizAdminRemove },
  { path: 'alcanyiz/questiongame', component: RoutedAlcanyizGame },
  { path: 'soares/user/plist', component: SoaresRoutedUserPlist },
  { path: 'soares/user/temas', component: PreguntasPorTemaComponent },
  { path: 'soares/user/new', component: SoaresRoutedAdminNew },
  { path: 'soares/admin/plist', component: SoaresRoutedAdminPlist },
  { path: 'soares/admin/new', component: SoaresRoutedAdminNew },
  { path: 'soares/admin/edit/:id', component: SoaresRoutedAdminEdit },
  { path: 'soares/admin/remove/:id', component: SoaresRoutedAdminRemove },
];
